Fix release failure by fetching all tags during checkout
Command:
  for remote in local_repo.remotes:
      remote.fetch('--tags')

Error message:
  git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
    cmdline: git fetch -v -- origin --tags
    stderr: 'fatal: couldn't find remote ref --tags'

Before:
    Fetching the repository
    /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin [...]

After:
    Fetching the repository
    /usr/bin/git -c protocol.version=2 fetch --prune --progress --no-recurse-submodules origin [...]