Fix unit test failure due to unresolvable dependencies.
Error 1:
  $ composer require phpunit/phpunit:5.7.*
  Your requirements could not be resolved to an installable set of packages.

Error 2:
  Fatal error: Uncaught Error: unknown class PHPUnit_Framework_TestCase in PHPCurlClassTest.php:9